services:
  - type: web
    name: library-management-backend
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: library_management
